# Layout

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false



# Naming

Naming/AccessorMethodName:
  Enabled: false

# Style

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
