# Layout

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 120

# Metrics

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Naming

Naming/AccessorMethodName:
  Enabled: false

# Style

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Lint/StructNewOverride:
  Enabled: false
