require 'kkm/kkm'
require 'kkm/constants'
require 'kkm/constants/cheque_type'
require 'kkm/constants/mode'
require 'kkm/constants/report_type'
require 'kkm/constants/register_number'
require 'kkm/constants/text_wrap'
require 'kkm/constants/tax_number'
require 'kkm/constants/payment_type'
require 'kkm/constants/alignment'
require 'kkm/constants/fiscal_property'
require 'kkm/constants/fiscal_property_type'
require 'kkm/errors'
require 'kkm/device_interface'
require 'kkm/device'
require 'kkm/version'
require 'builder'
require 'yaml'

module Kkm
end
