require 'kkm/kkm'
require 'kkm/constants'
require 'kkm/constants/agent_type'
require 'kkm/constants/position_type'
require 'kkm/constants/position_payment_type'
require 'kkm/constants/ffd_version'
require 'kkm/constants/cheque_type'
require 'kkm/constants/mode'
require 'kkm/constants/report_type'
require 'kkm/constants/register_number'
require 'kkm/constants/text_wrap'
require 'kkm/constants/tax'
require 'kkm/constants/tax_number'
require 'kkm/constants/payment_type'
require 'kkm/constants/alignment'
require 'kkm/constants/fiscal_property'
require 'kkm/constants/fiscal_property_type'
require 'kkm/constants/command'
require 'kkm/constants/error_code'
require 'kkm/device_driver_error'
require 'kkm/device_interface'
require 'kkm/device'
require 'kkm/version'
require 'yaml'

module Kkm
end
